"""
IOPY
~~~~

Python implementation to create or extract .iop files generated by IOPManager (fork of Ziparchive by Artpol, used by Lost Saga).

"""

__author__ = 'Trisnox'
__license__ = 'MIT'
__version__ = '1.0.0'

from .iopy import IOPY